export const PHONE_VERIFICATION_REQUEST = 'PHONE_VERIFICATION_REQUEST';
export const PHONE_VERIFICATION_SUCCESS = 'PHONE_VERIFICATION_SUCCESS';
export const PHONE_VERIFICATION_ERROR = 'PHONE_VERIFICATION_ERROR';
export const SET_PHONE = 'SET_PHONE';
export const SET_CODE = 'SET_CODE';

export const CLEAR_CODE = 'CLEAR_CODE';


export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const LOGOUT = 'LOGOUT';