export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';

export const SET_PENALTY_DATA = 'SET_PENALTY_DATA';
export const CREATE_PENALTY_REQUEST = 'CREATE_PENALTY_REQUEST';
export const CREATE_PENALTY_SUCCESS = 'CREATE_PENALTY_SUCCESS';
export const CREATE_PENALTY_ERROR = 'CREATE_PENALTY_ERROR';

export const CLEAR_PENALTY = 'CLEAR_PENALTY';
